/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects and checked in here so
// the starter compiles cleanly before the first local dev run.
